# Generated by Django 4.1.4 on 2022-12-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customer_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='isverified',
            field=models.BooleanField(db_column='IsVerified', default=False),
        ),
        migrations.AlterField(
            model_name='purchaseordertransaction',
            name='datedelivered',
            field=models.DateField(blank=True, db_column='DateDelivered', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordertransaction',
            name='isdelivered',
            field=models.BooleanField(db_column='IsDelivered', default=True),
        ),
        migrations.AlterField(
            model_name='purchaseordertransaction',
            name='ponumber',
            field=models.ForeignKey(db_column='PONumber', on_delete=django.db.models.deletion.CASCADE, to='base.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst',
            field=models.CharField(db_column='GST', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ntn',
            field=models.CharField(db_column='NTN', max_length=8, unique=True),
        ),
    ]
