# Generated by Django 4.1.4 on 2022-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_pricerate_price_rate_check_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='advancepayment',
            field=models.FloatField(db_column='AdvancePayment', verbose_name='Advance Payment (0-1)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='advancepaymenttrxid',
            field=models.CharField(db_column='AdvancePaymentTrxID', max_length=20, unique=True, verbose_name='Advance Payment TRX ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='finalpaymenttrxid',
            field=models.CharField(blank=True, db_column='FinalPaymentTrxID', default=None, max_length=20, null=True, unique=True, verbose_name='Final Payment TRX ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='podeliverydate',
            field=models.DateField(db_column='PODeliveryDate', verbose_name='Purchase Order Delievery Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ponumber',
            field=models.CharField(db_column='PONumber', max_length=10, primary_key=True, serialize=False, verbose_name='Purchase Order Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaseinvoicenum',
            field=models.CharField(blank=True, db_column='PurchaseInvoiceNum', default=None, max_length=10, null=True, verbose_name='Purchase Invoice Number'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst',
            field=models.CharField(db_column='GST', max_length=13, unique=True, verbose_name='Seller GST'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='IsActive', default=True, verbose_name='Seller Active or Not'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ntn',
            field=models.CharField(db_column='NTN', max_length=8, unique=True, verbose_name='Seller NTN'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellercode',
            field=models.CharField(db_column='SellerCode', max_length=13, primary_key=True, serialize=False, verbose_name='Seller Code'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellername',
            field=models.CharField(db_column='SellerName', max_length=50, verbose_name='Seller Name'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseordertransaction',
            unique_together={('ponumber', 'potransactionnum', 'productcode', 'supplypointcode')},
        )
    ]
