# Generated by Django 4.1.4 on 2022-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_pricerate_price_rate_check_2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseordertransaction',
            unique_together={('ponumber', 'productcode', 'supplypointcode')},
        )
    ]
