# Generated by Django 4.1.4 on 2022-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_pricerate_price_rate_check_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseordertransaction',
            name='potransactionnum',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='totalpayableamount',
            field=models.FloatField(blank=True, db_column='TotalPayableAmount'),
        ),
        migrations.AlterField(
            model_name='purchaseordertransaction',
            name='isdelivered',
            field=models.BooleanField(db_column='IsDelivered', default=False),
        )
    ]
